#!/usr/bin/env bash
# Install RouterBot as a systemd service (survives reboot / power loss).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_NAME="${ROUTERBOT_SERVICE_NAME:-routerbot}"
TS_SERVICE_NAME="${ROUTERBOT_TS_SERVICE_NAME:-routerbot-tailscale}"
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
TS_UNIT_PATH="/etc/systemd/system/${TS_SERVICE_NAME}.service"
ENV_PATH="/etc/routerbot/environment"

# User that owns CLI auth (~/.codex, ~/.cursor, etc.). Defaults to repo owner.
ROUTERBOT_USER="${ROUTERBOT_USER:-$(stat -c '%U' "$REPO_DIR")}"
ROUTERBOT_GROUP="${ROUTERBOT_GROUP:-$(id -gn "$ROUTERBOT_USER" 2>/dev/null || echo "$ROUTERBOT_USER")}"

pick_node() {
  if [[ -n "${ROUTERBOT_NODE:-}" && -x "${ROUTERBOT_NODE}" ]]; then
    echo "$ROUTERBOT_NODE"
    return
  fi
  if command -v node >/dev/null 2>&1; then
    local n
    n="$(command -v node)"
    # Cursor's bundled node is not suitable for a system service
    if [[ "$n" != *".cursor-server"* ]]; then
      echo "$n"
      return
    fi
  fi
  if [[ -x /usr/bin/node ]]; then
    echo /usr/bin/node
    return
  fi
  local nvm_glob="${HOME}/.nvm/versions/node/"*/bin/node
  # shellcheck disable=SC2086
  for candidate in $nvm_glob; do
    if [[ -x "$candidate" ]]; then
      echo "$candidate"
      return
    fi
  done
  echo "ERROR: Could not find node. Set ROUTERBOT_NODE=/path/to/node" >&2
  exit 1
}

NODE_BIN="$(sudo -u "$ROUTERBOT_USER" bash -c "$(declare -f pick_node); pick_node")"

build_path() {
  local home
  home="$(getent passwd "$ROUTERBOT_USER" | cut -d: -f6)"
  local parts=()
  # nvm default node (newest installed)
  local nvm_glob="${home}/.nvm/versions/node/"*/bin
  # shellcheck disable=SC2086
  for d in $nvm_glob; do
    [[ -d "$d" ]] && parts+=("$d")
  done
  parts+=(
    "${home}/.local/bin"
    /usr/local/bin
    /usr/bin
    /bin
  )
  local IFS=:
  echo "${parts[*]}"
}

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Re-running with sudo to install ${UNIT_PATH} ..."
  exec sudo env \
    ROUTERBOT_USER="$ROUTERBOT_USER" \
    ROUTERBOT_GROUP="$ROUTERBOT_GROUP" \
    ROUTERBOT_NODE="${ROUTERBOT_NODE:-}" \
    "$0" "$@"
fi

mkdir -p /etc/routerbot
PATH_VALUE="$(build_path)"
cat >"$ENV_PATH" <<EOF
# Generated by scripts/install-systemd.sh — edit and run: sudo systemctl restart routerbot
HOME=$(getent passwd "$ROUTERBOT_USER" | cut -d: -f6)
PATH=${PATH_VALUE}
NODE_ENV=production
EOF
chmod 644 "$ENV_PATH"

sed \
  -e "s|%ROUTERBOT_USER%|${ROUTERBOT_USER}|g" \
  -e "s|%ROUTERBOT_GROUP%|${ROUTERBOT_GROUP}|g" \
  -e "s|%ROUTERBOT_DIR%|${REPO_DIR}|g" \
  -e "s|%NODE_BIN%|${NODE_BIN}|g" \
  "${REPO_DIR}/deploy/routerbot.service" >"$UNIT_PATH"

sed \
  -e "s|%ROUTERBOT_DIR%|${REPO_DIR}|g" \
  "${REPO_DIR}/deploy/routerbot-tailscale.service" >"$TS_UNIT_PATH"

systemctl daemon-reload
systemctl enable "${TS_SERVICE_NAME}.service"
systemctl enable "${SERVICE_NAME}.service"
systemctl start "${TS_SERVICE_NAME}.service" || true
systemctl restart "${SERVICE_NAME}.service"

echo ""
echo "Installed ${UNIT_PATH}"
echo "Environment: ${ENV_PATH}"
echo "User:        ${ROUTERBOT_USER}"
echo "Node:        ${NODE_BIN}"
echo ""
systemctl status "${SERVICE_NAME}.service" --no-pager -l || true
echo ""
echo "Useful commands:"
echo "  ./scripts/check-routerbot.sh"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo systemctl status ${TS_SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
echo "  sudo systemctl restart ${SERVICE_NAME}"
